CREATE DATABASE SM
USE SM
CREATE TABLE PRODUCTS(
ID INT IDENTITY,
PNAME VARCHAR(150),
PRICE FLOAT,
QUANTITY INT,
INSTOCK INT NOT NULL DEFAULT 1,
PRIMARY KEY(ID)
)

SELECT * FROM PRODUCTS

UPDATE PRODUCTS SET PNAME = 'LUX SOAP',QUANTITY = 10
WHERE ID =2

CREATE PROC spAddData
@PNAME VARCHAR(150),
@PRICE FLOAT,
@QUANTITY INT
AS
BEGIN
INSERT INTO PRODUCTS(PNAME,PRICE,QUANTITY) VALUES(@PNAME,@PRICE,@QUANTITY)
END




spAddData 'juice',35.50,10


SELECT * FROM PRODUCTS

CREATE PROC spCHECKSTOCK
@ID INT
AS
BEGIN
DECLARE @QUU INT
SET @QUU = (SELECT QUANTITY FROM PRODUCTS WHERE ID =@ID)
IF @QUU >0
	UPDATE PRODUCTS SET INSTOCK = 1 WHERE ID = @ID
ELSE
	UPDATE PRODUCTS SET INSTOCK = 0 WHERE ID =@ID

END

UPDATE PRODUCTS SET QUANTITY = 10 WHERE ID =2


spCHECKSTOCK 2


CREATE PROC spMakePurchase
@ID INT,
@QT INT
AS
BEGIN
DECLARE @QUT INT
SET @QUT = (SELECT QUANTITY FROM PRODUCTS WHERE ID = @ID)
IF @QUT >= @QT
UPDATE PRODUCTS SET QUANTITY = QUANTITY-@QT
WHERE ID = @ID
		SET @QUT = (SELECT QUANTITY FROM PRODUCTS WHERE ID = @ID)
		IF @QUT = 0
			UPDATE PRODUCTS SET INSTOCK =0
			WHERE ID = @ID
ELSE
PRINT 'OUT OF STOCK'
END

DROP PROC spMakePurchase
SELECT * FROM PRODUCTS

spMakePurchase 1,4
SELECT * FROM PRODUCTS