select * from BOOK

BEGIN
SELECT * FROM BOOK
INSERT INTO BOOK VALUES(1,'NEW BOOK')
SELECT @@ERROR
--SELECT @@IDENTITY
--SELECT @@SERVERNAME,@@VERSION,@@LANGUAGE
END

SELECT * FROM employees
SELECT MAX(salary) FROM employees
UPDATE employees SET salary = 25000
WHERE employee_id= 100

BEGIN
DECLARE @MAXSAL INT  
SET @MAXSAL = (SELECT MAX(SALARY) FROM employees)
SELECT * FROM employees
WHERE salary = @MAXSAL
END


BEGIN 
DECLARE @MAXSAL INT
DECLARE @MINSAL INT
DECLARE @TOTALEMP INT
DECLARE @TOCOMEMP INT
DECLARE @TOTALEMPDPT INT
SET @MAXSAL = (SELECT MAX(SALARY) FROM employees)
SET @MINSAL = (SELECT MIN(SALARY) FROM employees)
SET @TOTALEMP = (SELECT COUNT(*) FROM employees)
SET @TOCOMEMP = (SELECT COUNT(*) FROM employees WHERE commission_pct IS NOT NULL)
SET @TOTALEMPDPT = (SELECT COUNT(*) FROM employees WHERE department_id = 90)
PRINT 'MAX SALARY : ' + CONVERT(VARCHAR,@MAXSAL)
PRINT 'MIN SALARY : ' + CONVERT(VARCHAR,@MINSAL)
PRINT 'TOTAL # OF EMP : ' + CONVERT(VARCHAR,@TOTALEMP)
PRINT 'TOTAL # OF  COMMISION EMP : ' + CONVERT(VARCHAR,@TOCOMEMP)
END


BEGIN 
DECLARE @NUM INT
SET @NUM = 25
PRINT 'TOTAL NUMBER : ' + CONVERT(VARCHAR,@NUM)
END
